-- MOSTRAR EL MES Y AÑO DONDE HUBO MAYOR GASTO DE DISTRACCIÓN POR CADA FAMILIA
DROP VIEW MAYOR_GASTO;
CREATE VIEW MAYOR_GASTO AS
SELECT HF.ID_FAMILIA, HF.MES, HF.AÑO, HF.DISTRACCION 
FROM HISTORIALFINANZAS HF ,(SELECT ID_FAMILIA, MAX(DISTRACCION) AS MAX_VALOR FROM HISTORIALFINANZAS GROUP BY ID_FAMILIA) AS T
WHERE T.ID_FAMILIA = HF.ID_FAMILIA AND HF.DISTRACCION = T.MAX_VALOR  ORDER BY ID_FAMILIA ASC;

-- CUÁL ES EL USUARIO DE MIEMBROS DE CADA FAMILIA QUE MÁS HA ENVIADO MENSAJES
CREATE VIEW USUARIO_CON_MAS_MENSAJES AS
SELECT T2.ID_FAMILIA, T2.USUARIOMF, T1.MAXIMO
FROM (SELECT  MF.ID_FAMILIA, MAX(A.MAX_ENVIA) AS MAXIMO 
FROM (SELECT USUARIOMF,COUNT(ID_MENSAJE) AS MAX_ENVIA FROM BUZON GROUP BY USUARIOMF) AS A , MIEMBROS_FAMILIA MF 
WHERE MF.USUARIOMF = A.USUARIOMF GROUP BY ID_FAMILIA) AS T1, (SELECT MF.ID_FAMILIA, MF.USUARIOMF,COUNT(ID_MENSAJE) AS MAX_ENVIA FROM BUZON B, MIEMBROS_FAMILIA MF
WHERE MF.USUARIOMF = B.USUARIOMF GROUP BY USUARIOMF) AS T2
WHERE T2.ID_FAMILIA = T1.ID_FAMILIA AND T2.MAX_ENVIA = T1.MAXIMO;
	
-- MOSTRAR EL REPORTE FINANCIERO DE CADA FAMILIA (REPORTE DETALLADO)  DEL 2020
CREATE VIEW REPORTE_POR_FAMILIA_2020 AS
SELECT SUM(TOTAL_GASTOS) AS TOTAL_GASTOS_AÑO, SUM(TOTAL_INGRESOS)AS TOTAL_INGRESOS_AÑO, SUM(TOTAL_INGRESOS-TOTAL_GASTOS) AS RESUMEN ,SUM(ALIMENTACION),SUM(SALUD) ,SUM(VIVIENDA) ,SUM(VESTIMENTA), SUM(DISTRACCION),  ID_FAMILIA 
FROM HISTORIALFINANZAS WHERE AÑO = 2020 GROUP BY ID_FAMILIA;
