CREATE TABLE HOGAR(
ID_HOGAR INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
NOMBRE_FAMILIA VARCHAR(50)
);
CREATE TABLE ADMINISTRADOR(
USUARIO VARCHAR(15) PRIMARY KEY NOT NULL UNIQUE,
CONTRASEÑA VARCHAR(15) NOT NULL,
ID_FAMILIA INT NOT NULL,
CONSTRAINT FK_FAMILIA FOREIGN KEY (ID_FAMILIA) REFERENCES HOGAR(ID_HOGAR)
);
CREATE TABLE MIEMBROS_FAMILIA(
USUARIOMF VARCHAR(15) PRIMARY KEY NOT NULL UNIQUE,
CONTRASEÑA VARCHAR(15) NOT NULL,
ID_FAMILIA INT NOT NULL,
CONSTRAINT FK_FAMILIA_MIEMBROS FOREIGN KEY (ID_FAMILIA) REFERENCES HOGAR(ID_HOGAR)
);
create table USUARIOS(
USUARIO varchar(15) PRIMARY KEY NOT NULL UNIQUE ,
CUENTA_BANCARIA varchar(15) NOT NULL UNIQUE,
VALOR numeric(8,2) NOT NULL, 
FAMILIA INT NOT NULL,
CONSTRAINT FK_USU_FAMILIA FOREIGN KEY (FAMILIA) REFERENCES HOGAR(ID_HOGAR)
);
CREATE TABLE CATEGORIAS(
ID_CATEGORIA INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT,
NOMBRE varchar(15)
);
CREATE TABLE GASTOS(
NOMBRE varchar(100) NOT NULL,
VALOR numeric(8,2) NOT NULL,  
FECHA_EMISION date,
FECHA_VENCIMIENTO date,
USUARIO_ADMIN VARCHAR(15) NOT NULL,
ID_CATEGORIA INT NOT NULL,
USUARIO varchar(15) NOT NULL,
CONSTRAINT FK_GAS_AD FOREIGN KEY (USUARIO_ADMIN) references ADMINISTRADOR(USUARIO),
CONSTRAINT FK_GAS_CAT FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIAS(ID_CATEGORIA),
CONSTRAINT FK_GAS_USU FOREIGN KEY (USUARIO) REFERENCES USUARIOS(USUARIO),
CONSTRAINT PK_GASTOS PRIMARY KEY (NOMBRE,USUARIO_ADMIN)
);
CREATE TABLE BUZON(
ID_MENSAJE INT PRIMARY KEY NOT NULL UNIQUE AUTO_INCREMENT, 
MENSAJE VARCHAR(200) NOT NULL,
USUARIO_ADMIN VARCHAR(15) NOT NULL,
USUARIOMF VARCHAR(15) NOT NULL,
NOMBRE_GASTOS VARCHAR(100),
FECHA DATE,
HORA TIME,
CONSTRAINT FK_BUZ_AD FOREIGN KEY (USUARIO_ADMIN) REFERENCES ADMINISTRADOR(USUARIO),
CONSTRAINT FK_BUZ_MF FOREIGN KEY (USUARIOMF) REFERENCES MIEMBROS_FAMILIA(USUARIOMF),
CONSTRAINT FK_BUZ_GAS FOREIGN KEY (NOMBRE_GASTOS) REFERENCES GASTOS(NOMBRE)
);
CREATE TABLE INGRESOS(
USUARIO VARCHAR(15) PRIMARY KEY NOT NULL UNIQUE,
USUARIO_ADMIN VARCHAR(15) NOT NULL,
CONSTRAINT FK_ING_USU FOREIGN KEY (USUARIO) REFERENCES USUARIOS(USUARIO),
CONSTRAINT FK_ING_AD FOREIGN KEY (USUARIO_ADMIN) REFERENCES ADMINISTRADOR(USUARIO)
);
CREATE TABLE HISTORIALFINANZAS(
MES VARCHAR(10) CHECK(MES IN ("ENERO","FEBRERO","MARZO","ABRIL","MAYO","JUNIO","JULIO","AGOSTO","SEPTIEMBRE","OCTUBRE","NOVIEMBRE","DICIEMBRE")),
AÑO INT(4) CHECK(AÑO > 2000),
TOTAL_GASTOS NUMERIC,
TOTAL_INGRESOS NUMERIC,
RESUMEN_EXCEDENTE NUMERIC,
ALIMENTACION NUMERIC,
SALUD NUMERIC,
VIVIENDA NUMERIC,
VESTIMENTA NUMERIC,
DISTRACCION NUMERIC,
ID_FAMILIA  INT NOT NULL,
CONSTRAINT PK_HF_MA PRIMARY KEY (MES,AÑO),
CONSTRAINT FK_HF_FAMILIA FOREIGN KEY (ID_FAMILIA) REFERENCES HOGAR(ID_HOGAR)
);