-- Para cada tabla, una consulta general, en donde se retornen todos los campos (por ejemplo, una consulta para retornar todos los usuarios),
SELECT * FROM HOGAR;
SELECT * FROM ADMINISTRADOR;
SELECT * FROM MIEMBROS_FAMILIA;
SELECT * FROM CATEGORIAS;
SELECT * FROM INGRESOS;
SELECT * FROM USUARIOS;
SELECT * FROM BUZON;
SELECT * FROM GASTOS;
SELECT * FROM HISTORIALFINANZAS;
-- Para cada tabla, una consulta de ids, en donde se retorne solamente el id de la tabla (por ejemplo, retornar el id de todos los usuarios).
SELECT ID_HOGAR FROM HOGAR;
SELECT USUARIO FROM ADMINISTRADOR;
SELECT USUARIOMF FROM MIEMBROS_FAMILIA;
SELECT ID_CATEGORIA FROM CATEGORIAS;
SELECT USUARIO FROM INGRESOS;
SELECT USUARIO FROM USUARIOS;
SELECT ID_MENSAJE FROM BUZON;
SELECT NOMBRE, USUARIO_ADMIN FROM GASTOS;
SELECT MES, AÑO FROM HISTORIALFINANZAS;
-- Para cada tabla, una consulta donde se utilice algún tipo de búsqueda (condición where) - (por ejemplo, retornar aquellos usuarios cuyo apellido empieza en 'B').
SELECT * FROM HOGAR WHERE NOMBRE_FAMILIA LIKE "P%";
SELECT * FROM ADMINISTRADOR WHERE ID_FAMILIA = 2;
SELECT * FROM MIEMBROS_FAMILIA WHERE USUARIOMF LIKE "D%";
SELECT * FROM CATEGORIAS WHERE NOMBRE = "VIVIENDA";
SELECT * FROM INGRESOS WHERE USUARIO LIKE "S%";
SELECT * FROM USUARIOS WHERE VALOR > 15000;
SELECT * FROM BUZON WHERE FECHA BETWEEN '2021-03-00' AND '2021-03-31';
SELECT * FROM GASTOS WHERE NOMBRE = "Agua";
SELECT * FROM HISTORIALFINANZAS WHERE ALIMENTACION > 5000;

-- La mitad de los reportes indicados en la documentación.
-- Mostrar el mes y año donde hubo mayor gasto de distracción
SELECT MES, AÑO, DISTRACCION FROM HISTORIALFINANZAS WHERE DISTRACCION = (SELECT MAX(DISTRACCION) FROM HISTORIALFINANZAS);
-- En que mes el resumen excedente fue el más bajo
SELECT MES, RESUMEN_EXCEDENTE FROM HISTORIALFINANZAS WHERE RESUMEN_EXCEDENTE = (SELECT MIN(RESUMEN_EXCEDENTE) FROM HISTORIALFINANZAS);
-- Cuál es el usuario de miembros de la familia que más ha enviado mensajes
SELECT USUARIOMF,COUNT(ID_MENSAJE) AS MAS_ENVIOS FROM BUZON GROUP BY USUARIOMF HAVING MAS_ENVIOS = (SELECT MAX(R.MAS_ENVIA) FROM (SELECT USUARIOMF,COUNT(ID_MENSAJE) AS MAS_ENVIA FROM BUZON GROUP BY USUARIOMF) AS R);
-- Mostrar el valor total por categoría en el 2020
SELECT AÑO, SUM(ALIMENTACION) AS TOTAL_ALIMETACION, SUM(SALUD) AS TOTAL_SALUD, SUM(VIVIENDA) AS TOTAL_VIVIENDA, SUM(VESTIMENTA) AS TOTAL_VESTIMENTA, SUM(DISTRACCION) AS TOTAL_DISTACCION FROM HISTORIALFINANZAS GROUP BY AÑO HAVING AÑO = 2020;
-- Total Gastos Y Total Ingresos del año 2021
SELECT SUM(TABLA.TOTAL_GASTOS) AS TOTAL_G, SUM(TABLA.TOTAL_INGRESOS) AS TOTAL_I FROM (SELECT TOTAL_GASTOS, TOTAL_INGRESOS FROM HISTORIALFINANZAS WHERE AÑO = 2020) AS TABLA;