-- MOSTRAR EL MES Y AÑO DONDE HUBO MAYOR GASTO DE DISTRACCIÓN
CREATE VIEW MAYOR_GASTO AS
SELECT MES, AÑO, DISTRACCION FROM HISTORIALFINANZAS WHERE DISTRACCION = (SELECT MAX(DISTRACCION) FROM HISTORIALFINANZAS);


-- CUÁL ES EL USUARIO DE MIEMBROS DE LA FAMILIA QUE MÁS HA ENVIADO MENSAJES
CREATE VIEW USUARIO_CON_MAS_MENSAJES AS
SELECT USUARIOMF,COUNT(ID_MENSAJE) AS MAS_ENVIOS FROM BUZON GROUP BY USUARIOMF HAVING MAS_ENVIOS = (SELECT MAX(R.MAS_ENVIA) 
FROM (SELECT USUARIOMF,COUNT(ID_MENSAJE) AS MAS_ENVIA FROM BUZON GROUP BY USUARIOMF) AS R);
	
-- MOSTRAR LOS USUARIOS QUE TENGAN INGRESOS MENOR A 3500    
CREATE VIEW INGRESOSBD AS SELECT*FROM USUARIOS WHERE VALOR<3500;


